## A basic GitHub Actions workflow for your Quarkus application.

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  QUARKUS_CONTAINER_IMAGE_USERNAME: ${{ secrets.DOCKER_HUB_LOGIN }}
  QUARKUS_CONTAINER_IMAGE_PASSWORD: ${{ secrets.DOCKER_HUB_PWD }}
  MVN_SETTINGS: ${{ secrets.MVN_SETTINGS }}
  GPG_KEY: ${{ secrets.GPG_KEY }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
        
      - name: Build
        run: |
          echo ${MVN_SETTINGS} > /tmp/settings.xml
          echo -n "$GPG_KEY" | base64 --decode | gpg --import
          mvn deploy -s /tmp/settings.xml
          rm -f /tmp/settings.xml
          rm -rf /home/runner/.gpg
